title = "Cable Kitten"
baseURL = "https://cablekitten.co.uk/"
languageCode = "en-us"
theme = 'ananke'
resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = false

[author]
  twitter = "https://twitter.com/AlickMitchell/"
  email = "alickmitchell@protonmail.com"
  name = "Cable Kitten"

[languages]
  [languages.en]
    title = "Cable Kitten"
    weight = 1
    contentDir = "content/"
    # languageDirection = 'rtl' for Right-To-Left languages

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = "Alick"
  favicon = "favicon-16x16.png"
  site_logo = ""
  description = "Welcome to my site. Here youll find posts covering Networking, Linux and other things I find intresting"
  background_color_class = "bg-navy"
  recent_posts_number = 4

[[params.ananke_socials]]
  name = "twitter"
  url = "https://twitter.com/AlickMitchell/"

[[menu.main]]
  name = "About"
  pageRef = "/abouts"
  weight = 2
